2018-07-28 16:19:38,341 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:25]
2018-07-28 18:44:02,765 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-28 19:14:53,445 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-28 19:15:05,836 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-28 23:28:51,324 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-28 23:30:07,462 ERROR: Exception on /login/ [POST] [in /home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/allin/Code/Python/Allen_blog/app/main/views.py", line 41, in login
    if user is None or not user.check_password(form.password.data):
  File "/home/allin/Code/Python/Allen_blog/app/main/models.py", line 42, in check_password
    return check_password_hash(self.password_hash, password)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/werkzeug/security.py", line 245, in check_password_hash
    if pwhash.count('$') < 2:
AttributeError: 'NoneType' object has no attribute 'count'
2018-07-28 23:33:58,676 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-28 23:47:54,240 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-28 23:49:56,757 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-28 23:50:37,451 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-28 23:51:34,081 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-28 23:52:25,386 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 09:07:31,326 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 09:07:32,706 ERROR: Exception on / [GET] [in /home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/allin/Code/Python/Allen_blog/app/main/views.py", line 33, in index
    return render_template('index.html', title='Home page', posts=posts)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/allin/Code/Python/Allen_blog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/allin/Code/Python/Allen_blog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/allin/Code/Python/Allen_blog/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2018-07-29 09:07:33,142 ERROR: Exception on / [GET] [in /home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/allin/Code/Python/Allen_blog/app/main/views.py", line 33, in index
    return render_template('index.html', title='Home page', posts=posts)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/allin/Code/Python/Allen_blog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/allin/Code/Python/Allen_blog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/allin/Code/Python/Allen_blog/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2018-07-29 09:09:27,246 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
