2018-07-29 11:20:57,810 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:21:39,032 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:22:03,199 ERROR: Exception on /user/xx/ [GET] [in /home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/allin/Code/Python/Allen_blog/app/main/views.py", line 96, in user_profile
    return render_template('profile.html', user=user, posts=posts)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/allin/Code/Python/Allen_blog/app/templates/profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/allin/Code/Python/Allen_blog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/allin/Code/Python/Allen_blog/app/templates/profile.html", line 25, in block "content"
    {% include '_post.html' %}
  File "/home/allin/Code/Python/Allen_blog/app/templates/_post.html", line 5, in top-level template code
    <a href="{{ url_for('main.profile', username=post.author.username) }}">
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.profile' with values ['username']. Did you mean 'main.user_profile' instead?
2018-07-29 11:22:04,722 ERROR: Exception on /user/xx/ [GET] [in /home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/allin/Code/Python/Allen_blog/app/main/views.py", line 96, in user_profile
    return render_template('profile.html', user=user, posts=posts)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/allin/Code/Python/Allen_blog/app/templates/profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/allin/Code/Python/Allen_blog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/allin/Code/Python/Allen_blog/app/templates/profile.html", line 25, in block "content"
    {% include '_post.html' %}
  File "/home/allin/Code/Python/Allen_blog/app/templates/_post.html", line 5, in top-level template code
    <a href="{{ url_for('main.profile', username=post.author.username) }}">
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/allin/Software/anaconda/envs/allen_blog/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.profile' with values ['username']. Did you mean 'main.user_profile' instead?
2018-07-29 11:22:20,053 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:27:24,711 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:27:56,304 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:28:31,783 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:29:21,299 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:29:30,043 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:29:44,030 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:31:11,118 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:31:35,712 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:32:09,264 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:32:32,734 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:33:51,287 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:35:07,941 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
2018-07-29 11:35:20,642 INFO: Microblog startup [in /home/allin/Code/Python/Allen_blog/app/my_extensions/file_logger.py:32]
